name: mangakuy
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  chartboost: ^1.0.0
  cloud_firestore: ^4.8.1
  dio: ^5.2.1+1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.8.4
  horizontal_picker: ^1.2.0
  http: ^0.13.0
  image_picker: ^0.8.9
  permission_handler: ^10.3.0
  photo_view: ^0.14.0
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/1024.png'

flutter:
  uses-material-design: true

  assets:
    - assets/1024.png
