// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgvZdIZ1yk_tbBt_G9fsOmW2FVHE-0ZM',
    appId: '1:799889181142:web:08e2bda91d548205b1bc77',
    messagingSenderId: '799889181142',
    projectId: 'flutter-widget-ai',
    authDomain: 'flutter-widget-ai.firebaseapp.com',
    databaseURL: 'https://flutter-widget-ai-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-widget-ai.appspot.com',
    measurementId: 'G-TLQ3WJ0QGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnPLPeFj5RbzCfJEhSm4zJoGPpwqSgiOI',
    appId: '1:799889181142:android:0bd2c9c6f4da265bb1bc77',
    messagingSenderId: '799889181142',
    projectId: 'flutter-widget-ai',
    databaseURL: 'https://flutter-widget-ai-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-widget-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qWT0Z2eOLzt99DlqjOpkLLV5Bn5MbIU',
    appId: '1:799889181142:ios:399c19551dadc792b1bc77',
    messagingSenderId: '799889181142',
    projectId: 'flutter-widget-ai',
    databaseURL: 'https://flutter-widget-ai-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-widget-ai.appspot.com',
    androidClientId: '799889181142-h443a811ur2dbte8fgbiuc96s6mtpr5e.apps.googleusercontent.com',
    iosClientId: '799889181142-dcotaffsr780ie6363c52667d8rgjamv.apps.googleusercontent.com',
    iosBundleId: 'com.aisadev.mangakuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qWT0Z2eOLzt99DlqjOpkLLV5Bn5MbIU',
    appId: '1:799889181142:ios:9859d52359b2f5e2b1bc77',
    messagingSenderId: '799889181142',
    projectId: 'flutter-widget-ai',
    databaseURL: 'https://flutter-widget-ai-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-widget-ai.appspot.com',
    androidClientId: '799889181142-h443a811ur2dbte8fgbiuc96s6mtpr5e.apps.googleusercontent.com',
    iosClientId: '799889181142-u8luiakm26on5mj73e7pht15c4d64cc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangakuy.RunnerTests',
  );
}
